name: unified_payment
description: A Flutter package that provides a unified API for multiple payment providers (Stripe, PayPal, RazorPay, Paystack, Flutterwave) using a WebView-first approach.
version: 1.0.0+1
homepage: https://github.com/MehadiReaz/unified_payment
repository: https://github.com/MehadiReaz/unified_payment
issue_tracker: https://github.com/MehadiReaz/unified_payment/issues
documentation: https://github.com/MehadiReaz/unified_payment#readme

topics:
  - payment
  - stripe
  - webview
  - paypal
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  http: ^1.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_async: ^1.3.1
  test: ^1.24.9
  webview_flutter_platform_interface: ^2.8.0

flutter:
  # This package is a Dart package, no platform-specific assets needed